services:
  db:
    container_name: db
    image: postgres:17.4-bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    restart: unless-stopped
    networks:
      - app-network
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge